# [Info]
site_name: å‡°äº¦ # å·¦ä¸Šè§’æ ‡é¢˜
site_url: https://zju-zhz.github.io
site_author: zhz
site_description: zhz's site

# [Navigtion]
nav:
  - Home: 
    - Real Home: head.md
    - å†™åœ¨å‰é¢: index.md
  - About: about.md
  - Course: 
    - è¯´æ˜: ./course.md
    - è®¡ç®—æœºç³»ç»ŸäºŒ: 
      - è¯´æ˜: ç³»ç»ŸäºŒ/explain.md
      - OS Services & Structures: ç³»ç»ŸäºŒ/1. OS Services & Structures (11.7ã€11.14).md
      - OS Structures: ç³»ç»ŸäºŒ/2. OS Structures (11.17).md
      - Process: ç³»ç»ŸäºŒ/3. Process(11.17ã€11.21ã€11.24).md
      - Threads: ç³»ç»ŸäºŒ/4. Threads(11.24ã€11.28ã€12.1).md
      - Threads_b: ç³»ç»ŸäºŒ/5. Threads_b(12.1).md
      - CPU_Scheduling: ç³»ç»ŸäºŒ/6. CPU_Scheduling(12.5ã€12.8ã€12.12).md
      - Mars: ç³»ç»ŸäºŒ/7. Mars(12.12).md
      - Synchronization Tools: ç³»ç»ŸäºŒ/8. Synchronization Tools (12.14).md
    - fds:
      - è¯´æ˜: FDS/explain.md
      - exam: 
        - è¯´æ˜: FDS/è¯•å·/è¯•å·.md
        - 21-22æœŸä¸­å·: FDS/è¯•å·/21-22 æœŸä¸­å·.md
        - æœŸä¸­å·: FDS/è¯•å·/æœŸä¸­å·.md
      # - hw:
      #   - hw1-7: FDS/fds_hw/fds_hw1-7.md
      #   - hw8: FDS/fds_hw/fds_hw8.md
      #   - hw9: FDS/fds_hw/fds_hw9.md
      #   - hw10: FDS/fds_hw/fds_hw10.md
      #   - hw11: FDS/fds_hw/fds_hw11.md
      #   - hw12: FDS/fds_hw/fds_hw12.md
      #   - hw13: FDS/fds_hw/fds_hw13.md
      #   - hw14: FDS/fds_hw/fds_hw14.md
      #   - hw15: FDS/fds_hw/fds_hw15.md
      - lec:
        - lec1-6: FDS/fds_lec/fds_lec1-6.md
        - lec7: FDS/fds_lec/fds_lec7.md 
        - lec8: FDS/fds_lec/fds_lec8.md 
        - lec9: FDS/fds_lec/fds_lec9.md 
        - lec10: FDS/fds_lec/fds_lec10.md 
        - lec11: FDS/fds_lec/fds_lec11.md 
        - lec12: FDS/fds_lec/fds_lec12.md 
        - lec13-14: FDS/fds_lec/fds_lec13&&lec_14.md 
    - oop:
      - è¯´æ˜: OOP/explain.md
      - lec:
        - exam: OOP/oop_lec/oop_exam.md 
        - lec11: OOP/oop_lec/oop_lec11.md 
        - lec12: OOP/oop_lec/oop_lec12.md 
        - lec13: OOP/oop_lec/oop_lec13.md 
        - lec14: OOP/oop_lec/oop_lec14.md 
        - lec15: OOP/oop_lec/oop_lec15.md 
      - selfstudy:
        - self1: OOP/oop_self/oop_self1.md 
        - self2: OOP/oop_self/oop_self2.md 
        - self3: OOP/oop_self/oop_self3.md 
        - self4: OOP/oop_self/oop_self4.md 
        - self5: OOP/oop_self/oop_self5.md 
        - self6: OOP/oop_self/oop_self6.md 
        - self7: OOP/oop_self/oop_self7.md 
        - self8: OOP/oop_self/oop_self8.md 
        - self9: OOP/oop_self/oop_self9.md 
        - self10: OOP/oop_self/oop_self10.md 
    - æœºå™¨äººå¯¼è®º: 
      - ç¬¬ä¸‰è¯¾ å¾®æ§åˆ¶å™¨: æœºå™¨äººå¯¼è®º/å¾®æ§åˆ¶å™¨.md
      - ç¬¬å››è¯¾ æœºå™¨äººä¼ æ„Ÿå™¨: æœºå™¨äººå¯¼è®º/ä¼ æ„Ÿå™¨.md
    - ä¸­å›½ç°å½“ä»£å°è¯´èµæ: 
      - ä¸­å›½ç°å½“ä»£å°è¯´ç®€è„‰: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/ä¸­å›½ç°å½“ä»£å°è¯´èµæ.md
      - æ²ˆä»æ–‡å°è¯´èµæ: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/æ²ˆä»æ–‡å°è¯´èµæ.md
  - Friend: Friend/link.md
  - Strange: 
    - 209å¿—æ€ªå½•: Friend/pet.md
    - ä¸½æ³½ç§˜é—»: Friend/lize.md
  - Triviality:
    - ç½‘é¡µç¾åŒ–: çç¢/triviality.md
  
# [UI]
## [top]
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default # æ—¥é—´æ¨¡å¼
      primary: indigo # ä¸Šæ–¹çš„
      accent: orange # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      toggle:
        icon: material/weather-night # å›¾æ ‡
        name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
    - scheme: slate # å¤œé—´æ¨¡å¼
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼
  features:
    - navigation.tabs # ä½¿ç”¨Tabæ¥è¿›è¡Œåˆ†ç±»
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.indexes # Tabä¼šæœ‰ä¸€ä¸ªindex.md è€Œä¸æ˜¯åœ¨æ‰“å¼€Tabæ—¶æ‰“å¼€ç¬¬ä¸€ç¯‡æ–‡ç« 
    # - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
    - content.code.copy # å¯ä»¥é€šè¿‡æŒ‰é’®å¤åˆ¶ä»£ç 
    - content.code.annotate
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # ç¼–è¾‘æŒ‰é’®è·³è½¬çš„é“¾æ¥
## [top-right corner]
repo_url: https://github.com/ZJU-zhz/ZJU-zhz.github.io # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: ZJU-zhz.github.io # å³ä¸Šè§’çš„åå­—
## [bottom-left corner]
copyright: æœ±é•å“² CC-BY-NC-4.0 # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜
## [bottom-right corner]
extra:
  vssue: shafish  # éšä¾¿å¡«å€¼ï¼Œä¸»è¦æ˜¯è®¾ç½®{% set vssue = config.extra.vssue %}æ—¶ï¼Œvssueåˆå§‹å€¼å¯ç”¨
  social: # icons
    - icon: fontawesome/brands/weixin
      link: https://wx.qq.com/
      name: å¾®ä¿¡å· | zhz19357570421
    - icon: fontawesome/solid/paper-plane
      link: mailto:zjuzhz@outlook.com
      name: Outlook 
    - icon: fontawesome/brands/qq
      link: https://user.qzone.qq.com/750429346
      name: QQ | å‡°äº¦ # é¼ æ ‡æ‚¬æµ®æç¤º
    - icon: fontawesome/brands/github
      link: https://github.com/ZJU-zhz
      name: GitHub | ZJU-zhz
  analytics: 
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            è°¢è°¢æ”¯æŒ, væˆ‘äº”åğŸ¤—
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            ä¼šæ”¹çš„ğŸ˜­

# [Extensions]
plugins:
  - search: # ç°åœ¨è¿˜ä¸æ”¯æŒä¸­æ–‡æœç´¢ æ”¯æŒä¹‹åå¯ä»¥è®¾ç½®è¯­è¨€
    # insiderå·²ç»æ”¯æŒä¸­æ–‡çš„åˆ†è¯æœç´¢äº† https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # ç»™å•ç¯‡æ–‡ç« æ·»åŠ æ ‡ç­¾ https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - encryptcontent: {}
      #global_password: '1221504'
markdown_extensions:
  #åˆ—è¡¨
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true
  # latexæ”¯æŒ
  - pymdownx.arithmatex: 
      generic: true
  # ç»™å›¾ç‰‡åé¢æ·»åŠ {width="300"}è®¾ç½®å¤§å°
  - attr_list 
  - md_in_html
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      linenums: true # æ˜¾ç¤ºè¡Œå·
      auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.superfences # ä»£ç å—é«˜äº®æ’ä»¶
  - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonitionéœ€è¦
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables #è¡¨æ ¼
  - footnotes #æ³¨è„š
  #è¡¨æƒ…
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra_javascript:
  # latexæ”¯æŒ
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - java/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0

extra_css:
  - css/no-footer.css # ä¸ä½¿ç”¨åº•éƒ¨çš„ç¿»é¡µ
  - css/unordered-list-symbols.css # multiplt unordered list symbols
  - css/flink.css

