# [Info]
site_name: HowJulçš„å­¦ä¹ ç¬”è®° # å·¦ä¸Šè§’æ ‡é¢˜
site_url: https://howjul.github.io/note
site_author: zhz
site_description: zhz's site

# [Navigtion]
nav:
  - Home: 
    - Home: index.md
    - Secondary disease: head.md
    - About: about.md
  - Conclusion:
    - è¯´æ˜: ./è¯¾ç¨‹æ€»ç»“/index.md
    - å¤§ä¸‰æ˜¥å¤: ./è¯¾ç¨‹æ€»ç»“/å¤§ä¸‰æ˜¥å¤.md
    - å¤§ä¸‰ç§‹å†¬: ./è¯¾ç¨‹æ€»ç»“/å¤§ä¸‰ç§‹å†¬.md
    - å¤§äºŒæš‘å‡: ./è¯¾ç¨‹æ€»ç»“/å¤§äºŒæš‘å‡.md
    - å¤§äºŒæ˜¥å¤: ./è¯¾ç¨‹æ€»ç»“/å¤§äºŒæ˜¥å¤.md
    - å¤§äºŒç§‹å†¬: ./è¯¾ç¨‹æ€»ç»“/å¤§äºŒç§‹å†¬.md
    - å¤§ä¸€æš‘å‡: ./è¯¾ç¨‹æ€»ç»“/å¤§ä¸€æš‘å‡.md
    - å¤§ä¸€æ˜¥å¤: ./è¯¾ç¨‹æ€»ç»“/å¤§ä¸€æ˜¥å¤.md
    - å¤§ä¸€ç§‹å†¬: ./è¯¾ç¨‹æ€»ç»“/å¤§ä¸€ç§‹å†¬.md
  - Course: 
    - è¯´æ˜: ./course.md
    # - è®¡ç®—æœºç³»ç»Ÿä¸€: ç³»ç»Ÿä¸€/ç³»ç»Ÿä¸€.md
    - æŠ€æœ¯æ²Ÿé€š:
      - 1.æ–‡çŒ®æ£€ç´¢: æŠ€æœ¯æ²Ÿé€š/1 æ–‡çŒ®æ£€ç´¢.md
      - 2.æ–‡çŒ®é˜…è¯»: æŠ€æœ¯æ²Ÿé€š/2 æ–‡çŒ®é˜…è¯».md
      - 3.æ–‡çŒ®ç»¼è¿°: æŠ€æœ¯æ²Ÿé€š/3 æ–‡çŒ®ç»¼è¿°.md
      - 4.æŠ€æœ¯æ–‡æ¡£çš„ç»“æ„: æŠ€æœ¯æ²Ÿé€š/4 æŠ€æœ¯æ–‡æ¡£çš„ç»“æ„.md
      - 5.æŠ€æœ¯æ–‡æ¡£çš„è¯­è¨€: æŠ€æœ¯æ²Ÿé€š/5 æŠ€æœ¯æ–‡æ¡£çš„è¯­è¨€.md
      - 6.æ¼”ç¤ºæ–¹æ³•: æŠ€æœ¯æ²Ÿé€š/6 æ¼”ç¤ºæ–¹æ³•.md
      - 7.æ¼”è®²æ–¹æ³•: æŠ€æœ¯æ²Ÿé€š/7 æ¼”è®²æ–¹æ³•.md
    - è®¡ç®—æœºç³»ç»ŸäºŒ: 
      - 1.OS Services & Structures: ç³»ç»ŸäºŒ/1. OS Services & Structures (11.7ã€11.14).md
      - 2.OS Structures: ç³»ç»ŸäºŒ/2. OS Structures (11.17).md
      - 3.Process: ç³»ç»ŸäºŒ/3. Process(11.17ã€11.21ã€11.24).md
      - 4.Threads: ç³»ç»ŸäºŒ/4. Threads(11.24ã€11.28ã€12.1).md
      - 5.Threads_b: ç³»ç»ŸäºŒ/5. Threads_b(12.1).md
      - 6.CPU_Scheduling: ç³»ç»ŸäºŒ/6. CPU_Scheduling(12.5ã€12.8ã€12.12).md
      - 7.Mars: ç³»ç»ŸäºŒ/7. Mars(12.12).md
      - 8.Synchronization Tools: ç³»ç»ŸäºŒ/8. Synchronization Tools (12.14).md
    - æ•°æ®ç»“æ„åŸºç¡€:
      - exam: 
        - è¯´æ˜: FDS/è¯•å·/è¯•å·.md
        - 21-22æœŸä¸­å·: FDS/è¯•å·/21-22 æœŸä¸­å·.md
        - æœŸä¸­å·: FDS/è¯•å·/æœŸä¸­å·.md
      # - hw:
      #   - hw1-7: FDS/fds_hw/fds_hw1-7.md
      #   - hw8: FDS/fds_hw/fds_hw8.md
      #   - hw9: FDS/fds_hw/fds_hw9.md
      #   - hw10: FDS/fds_hw/fds_hw10.md
      #   - hw11: FDS/fds_hw/fds_hw11.md
      #   - hw12: FDS/fds_hw/fds_hw12.md
      #   - hw13: FDS/fds_hw/fds_hw13.md
      #   - hw14: FDS/fds_hw/fds_hw14.md
      #   - hw15: FDS/fds_hw/fds_hw15.md
      - lec:
        - lec1-6: FDS/fds_lec/fds_lec1-6.md
        - lec7: FDS/fds_lec/fds_lec7.md 
        - lec8: FDS/fds_lec/fds_lec8.md 
        - lec9: FDS/fds_lec/fds_lec9.md 
        - lec10: FDS/fds_lec/fds_lec10.md 
        - lec11: FDS/fds_lec/fds_lec11.md 
        - lec12: FDS/fds_lec/fds_lec12.md 
        - lec13-14: FDS/fds_lec/fds_lec13&&lec_14.md 
    - é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡:
      - lec:
        - exam: OOP/oop_lec/oop_exam.md 
        - lec11: OOP/oop_lec/oop_lec11.md 
        - lec12: OOP/oop_lec/oop_lec12.md 
        - lec13: OOP/oop_lec/oop_lec13.md 
        - lec14: OOP/oop_lec/oop_lec14.md 
        - lec15: OOP/oop_lec/oop_lec15.md 
      - selfstudy:
        - self1: OOP/oop_self/oop_self1.md 
        - self2: OOP/oop_self/oop_self2.md 
        - self3: OOP/oop_self/oop_self3.md 
        - self4: OOP/oop_self/oop_self4.md 
        - self5: OOP/oop_self/oop_self5.md 
        - self6: OOP/oop_self/oop_self6.md 
        - self7: OOP/oop_self/oop_self7.md 
        - self8: OOP/oop_self/oop_self8.md 
        - self9: OOP/oop_self/oop_self9.md 
        - self10: OOP/oop_self/oop_self10.md 
    - é«˜çº§æ•°æ®ç»“æ„ä¸ç®—æ³•åˆ†æ:
      - 1.AVL Tree&Splay Tree: ADS/1. AVL Tree&Splay Tree 2.28.md
      - 2.Red-Black Trees&B+ Trees: ADS/2. Red-Black Trees&B+ Trees3.7.md
      - 3.Inverted File Index: ADS/3. Inverted File Index.md
      - 4.Leftist Heaps and Skew Heaps: ADS/4. Leftist Heaps and Skew Heaps.md
      - 5.Binomial Queue: ADS/5. Binomial Queue.md
      - 6.Backtracking: ADS/6. Backtracking.md
      - 7.Divide and Conquer: ADS/7. Divide and Conquer.md
      - 8.Dynamic Programming: ADS/8. Dynamic Programming.md
      - 9.Greedy Algorithms: ADS/9. Greedy Algorithms.md
      - 10.NP-Completeness: ADS/10. NP-Completeness.md
      - 11.Approximation: ADS/11. Approximation.md
      - 12.Local Search: ADS/12. Local Search.md
      - 13.Randomized Algorithms: ADS/13. Randomized Algorithms.md
      - 14.Parallel Algorithms: ADS/14. Parallel Algorithms.md
      - 15.External Sorting: ADS/15. External Sorting.md
      - å‚è€ƒ: ADS/inference.md
    - è®¡ç®—æœºç³»ç»Ÿä¸‰:
      - ç¬¬3è¯¾: ç³»ç»Ÿä¸‰/ç¬¬ä¸‰è¯¾ 3.6.md
      - ç¬¬4è¯¾: ç³»ç»Ÿä¸‰/ç¬¬å››è¯¾ 3.9.md
      - ç¬¬5è¯¾: ç³»ç»Ÿä¸‰/ç¬¬äº”è¯¾ 3.13.md
      - ç¬¬6è¯¾: ç³»ç»Ÿä¸‰/ç¬¬å…­è¯¾ 3.16.md
      - ç¬¬7è¯¾: ç³»ç»Ÿä¸‰/ç¬¬ä¸ƒè¯¾ 3.20.md
      - ç¬¬8è¯¾: ç³»ç»Ÿä¸‰/ç¬¬å…«è¯¾ 3.23.md
      - ç¬¬9è¯¾: ç³»ç»Ÿä¸‰/ç¬¬ä¹è¯¾ 3.27.md
      - ç¬¬10è¯¾: ç³»ç»Ÿä¸‰/ç¬¬åè¯¾ 3.30.md
      - ç¬¬15è¯¾: ç³»ç»Ÿä¸‰/ç¬¬åäº”è¯¾ 4.17.md
      - ç¬¬16è¯¾: ç³»ç»Ÿä¸‰/ç¬¬16è¯¾ 4.20.md
      - ç¬¬17è¯¾: ç³»ç»Ÿä¸‰/ç¬¬17è¯¾ 4.24.md
      - ç¬¬18è¯¾: ç³»ç»Ÿä¸‰/ç¬¬18è¯¾ 4.27.md
      - ç¬¬19è¯¾: ç³»ç»Ÿä¸‰/ç¬¬19è¯¾ 5.4.md
      - ç¬¬20è¯¾: ç³»ç»Ÿä¸‰/ç¬¬20è¯¾ 5.8.md
      - ç¬¬21è¯¾: ç³»ç»Ÿä¸‰/ç¬¬21è¯¾ 5.11.md
      - ç¬¬22è¯¾: ç³»ç»Ÿä¸‰/ç¬¬22è¯¾ 5.15.md
      - ç¬¬23è¯¾: ç³»ç»Ÿä¸‰/ç¬¬23è¯¾ 5.18.md
      - ç¬¬24è¯¾: ç³»ç»Ÿä¸‰/ç¬¬24è¯¾ 5.22.md
      - ç¬¬25è¯¾: ç³»ç»Ÿä¸‰/ç¬¬25è¯¾ 5.25.md
      - ç¬¬26è¯¾: ç³»ç»Ÿä¸‰/ç¬¬26è¯¾ 5.29.md
      - ç¬¬27è¯¾: ç³»ç»Ÿä¸‰/ç¬¬27è¯¾ 6.1.md
      - ç¬¬28è¯¾: ç³»ç»Ÿä¸‰/ç¬¬28è¯¾ 6.5.md
      - ç¬¬29è¯¾: ç³»ç»Ÿä¸‰/ç¬¬29è¯¾ 6.8.md
      - æ“ä½œç³»ç»Ÿå¯¼è®ºç¬”è®°: ç³»ç»Ÿä¸‰/æ“ä½œç³»ç»Ÿå¯¼è®ºç¬”è®°.md
    - å¯†ç å­¦: å¯†ç å­¦/explain.md
    - è½¯ä»¶å®‰å…¨: 
      - 0.Introduce: è½¯ä»¶å®‰å…¨/0. Introduce.md
      - 1.Overview: è½¯ä»¶å®‰å…¨/1. Overview.md
      - 2.Basic Principles: è½¯ä»¶å®‰å…¨/2. Basic Principles.md
      - 3.Buffer Overflow: è½¯ä»¶å®‰å…¨/3. Buffer Overflow.md
      - 4.Ret2libc & ROP: è½¯ä»¶å®‰å…¨/4. Ret2libc & ROP.md
      - 5.ROP & BROP: è½¯ä»¶å®‰å…¨/5. ROP & BROP.md
      - 6.Format String Attack: è½¯ä»¶å®‰å…¨/6. æ ¼å¼åŒ–å­—ç¬¦ä¸²æ¼æ´.md
      - 7.Static Analysis: è½¯ä»¶å®‰å…¨/7. é™æ€åˆ†æ.md
      - 8.Symbolic&Concolic Execution: è½¯ä»¶å®‰å…¨/8. Symbolic&Concolic Execution.md
      - 9.Taint Analysis: è½¯ä»¶å®‰å…¨/9. Taint Analysis.md
      - 10.fuzz: è½¯ä»¶å®‰å…¨/10. fuzz.md
      - 11.SFI&CFI: è½¯ä»¶å®‰å…¨/11. SFI & CFI.md
    - æ•°æ®å®‰å…¨ä¸éšç§ä¿æŠ¤: 
      - 1.Course Overview: æ•°æ®å®‰å…¨/1. Course Overview.md
      - 2.User Authentication: æ•°æ®å®‰å…¨/2. User Authentication.md
      - 3.Unix Discretionary Access Control: æ•°æ®å®‰å…¨/3.  Unix Discretionary Access Control.md
      - 4.MAC and Intergrity Protection: æ•°æ®å®‰å…¨/4. MAC and Intergrity Protection.md
      - 5.Role Based Access Control: æ•°æ®å®‰å…¨/5. Role Based Access Control.md
      - 6.Modern Crypto: æ•°æ®å®‰å…¨/6. Modern Crypto.md
      - 7.Stream Ciphers and CPA Security: æ•°æ®å®‰å…¨/7. Stream Ciphers and CPA Security.md
      - 8.PRF, CPA Security and CCA Security: æ•°æ®å®‰å…¨/8. PRF, CPA Security and CCA Security.md
      - 9. Message Authentication Code: æ•°æ®å®‰å…¨/9. Message Authentication Code.md
      - 10. Number Theory Basics: æ•°æ®å®‰å…¨/10. Number Theory Basics.md
      - 11. Key Management and The Need for Public Key Cryptography: æ•°æ®å®‰å…¨/11. Key Management and The Need for Public Key Cryptography.md
      - 13. RSA Encryption: æ•°æ®å®‰å…¨/13. RSA Encryption.md
      - 14. Digital Signature: æ•°æ®å®‰å…¨/14. Digital Signature.md
      - 15. Differential Privacy: æ•°æ®å®‰å…¨/15. Differential Privacy.md
    - æœºå™¨äººå¯¼è®º: 
      - ç¬¬ä¸‰è¯¾ å¾®æ§åˆ¶å™¨: æœºå™¨äººå¯¼è®º/ç¬¬ä¸‰è¯¾ 3.6 å¾®æ§åˆ¶å™¨.md
      - ç¬¬å››è¯¾ æœºå™¨äººä¼ æ„Ÿå™¨: æœºå™¨äººå¯¼è®º/ç¬¬å››è¯¾ 3.10 æœºå™¨äººä¼ æ„Ÿå™¨.md
      - ç¬¬äº”è¯¾ æœºå™¨äººé©±åŠ¨åŸç†æ¦‚è¿°: æœºå™¨äººå¯¼è®º/ç¬¬äº”è¯¾ 3.13 æœºå™¨äººé©±åŠ¨åŸç†æ¦‚è¿°.md
      - ç¬¬å…­è¯¾ æœºå™¨äººé©±åŠ¨åŸç†æ¦‚è¿°-2: æœºå™¨äººå¯¼è®º/ç¬¬å…­è¯¾ 3.17 æœºå™¨äººé©±åŠ¨åŸç†æ¦‚è¿°-2.md
      - ç¬¬ä¸ƒè¯¾ æœºå™¨äººè®¾è®¡ä¸ä¼ åŠ¨-1: æœºå™¨äººå¯¼è®º/ç¬¬ä¸ƒè¯¾ 3.20 æœºå™¨äººè®¾è®¡ä¸ä¼ åŠ¨-1.md
      - ç¬¬å…«è¯¾ æœºå™¨äººè®¾è®¡ä¸ä¼ åŠ¨-2: æœºå™¨äººå¯¼è®º/ç¬¬å…«è¯¾ 3.24 æœºå™¨äººè®¾è®¡ä¸ä¼ åŠ¨-2.md
      - ç¬¬ä¹è¯¾ æœºå™¨äººè¿åŠ¨å­¦å’Œåæ ‡å˜æ¢: æœºå™¨äººå¯¼è®º/ç¬¬ä¹è¯¾ 3.27 æœºå™¨äººè¿åŠ¨å­¦å’Œåæ ‡å˜æ¢.md
      - ç¬¬åè¯¾ é‡Œç¨‹ä¼°è®¡: æœºå™¨äººå¯¼è®º/ç¬¬åè¯¾ 3.31 é‡Œç¨‹ä¼°è®¡.md
      - ç¬¬åä¸€è¯¾ æœºå™¨äººè§†è§‰: æœºå™¨äººå¯¼è®º/ç¬¬åä¸€è¯¾ 4.3 æœºå™¨äººè§†è§‰.md
      - ç¬¬åäºŒè¯¾ è§„åˆ’å¯¼è®º: æœºå™¨äººå¯¼è®º/ç¬¬åäºŒè¯¾ 4.7 è§„åˆ’å¯¼è®º.md
      - ç¬¬åä¸‰è¯¾ é›†ç¾¤: æœºå™¨äººå¯¼è®º/ç¬¬åä¸‰è¯¾ 4.10 é›†ç¾¤.md
    - ä¸­å›½ç°å½“ä»£å°è¯´èµæ: 
      - ä¸­å›½ç°å½“ä»£å°è¯´ç®€è„‰: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/ä¸­å›½ç°å½“ä»£å°è¯´èµæ.md
      - æ²ˆä»æ–‡å°è¯´èµæ: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/æ²ˆä»æ–‡å°è¯´èµæ.md
      - å¼ çˆ±ç²å°è¯´èµæ: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/å¼ çˆ±ç²å°è¯´èµæ.md
      - è°Œå®¹å°è¯´èµæ: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/è°Œå®¹å°è¯´èµæ.md
      - ä½™åå°è¯´èµæ: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/ä½™åå°è¯´èµæ.md
      - åˆ˜éœ‡äº‘å°è¯´èµæ: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/åˆ˜éœ‡äº‘å°è¯´èµæ.md
      - é¬¼å­å°è¯´èµæ: ä¸­å›½ç°å½“ä»£å°è¯´èµæ/é¬¼å­å°è¯´èµæ.md
  - ML: 
    - Gitå­¦ä¹ ç¬”è®°: ML/Git.md
    - Pythonå­¦ä¹ ç¬”è®°: ML/Python.md
    - Numpyå­¦ä¹ ç¬”è®°: ML/Numpy.md
    - Linuxå­¦ä¹ ç¬”è®°: ML/Linux.md
    - Pytorchå­¦ä¹ ç¬”è®°:
      - Pytorch1: ML/Pytorch1.md
      - Pytorch2: ML/Pytorch2.md
      - Pytorch3: ML/Pytorch3.md
    - æå®æ¯…æœºå™¨å­¦ä¹ è¯¾ç¨‹:
      - Lec1 Introduction of Deep Learning: ML/Lec1 Introduction of Deep Learning.md

  - Friend: Friend/link.md
  - Strange: 
    - 209å¿—æ€ªå½•: Friend/pet.md
    - ä¸½æ³½ç§˜é—»: Friend/lize.md
    - 1/365 night: Friend/night.md
  - Triviality:
    - ç½‘é¡µç¾åŒ–: çç¢/triviality.md
  
# [UI]
## [top]
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default # æ—¥é—´æ¨¡å¼
      primary: teal # ä¸Šæ–¹çš„
      accent: teal # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      toggle:
        icon: material/weather-night # å›¾æ ‡
        name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
    - scheme: slate # å¤œé—´æ¨¡å¼
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼
  # å¯¼èˆªæ 
  features:
    - navigation.tabs # ä½¿ç”¨Tabæ¥è¿›è¡Œåˆ†ç±»
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.indexes # Tabä¼šæœ‰ä¸€ä¸ªindex.md è€Œä¸æ˜¯åœ¨æ‰“å¼€Tabæ—¶æ‰“å¼€ç¬¬ä¸€ç¯‡æ–‡ç« 
    # - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
    - content.code.copy # å¯ä»¥é€šè¿‡æŒ‰é’®å¤åˆ¶ä»£ç 
    - content.code.annotate
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
    repo: fontawesome/brands/github
  logo: ./img/logo.jpg
  favicon: ./img/logo.ico
## edit_uri: edit/main/docs # ç¼–è¾‘æŒ‰é’®è·³è½¬çš„é“¾æ¥
## [top-right corner]
repo_url: https://github.com/howjul/note # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: note # å³ä¸Šè§’çš„åå­—
## [bottom-left corner]
copyright: HowJul. CC-BY-NC-4.0 # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜
## [bottom-right corner]
extra:
  vssue: shafish  # éšä¾¿å¡«å€¼ï¼Œä¸»è¦æ˜¯è®¾ç½®{% set vssue = config.extra.vssue %}æ—¶ï¼Œvssueåˆå§‹å€¼å¯ç”¨
  social: # icons
    - icon: fontawesome/brands/weixin
      link: https://wx.qq.com/
      name: å¾®ä¿¡å· | HowJul.(é‚®ç®±è”ç³»)
    - icon: fontawesome/solid/paper-plane
      link: mailto:zjuzhz@outlook.com
      name: Outlook 
    - icon: fontawesome/brands/qq
      link: https://user.qzone.qq.com
      name: QQ | å‡°äº¦(é‚®ç®±è”ç³») # é¼ æ ‡æ‚¬æµ®æç¤º
    - icon: fontawesome/brands/github
      link: https://github.com/howjul
      name: GitHub | howjul
  analytics: 
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            è°¢è°¢æ”¯æŒ, væˆ‘äº”åğŸ¤—
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            ä¼šæ”¹çš„ğŸ˜­

# [Extensions]
plugins:
  - search: # ç°åœ¨è¿˜ä¸æ”¯æŒä¸­æ–‡æœç´¢ æ”¯æŒä¹‹åå¯ä»¥è®¾ç½®è¯­è¨€
    # insiderå·²ç»æ”¯æŒä¸­æ–‡çš„åˆ†è¯æœç´¢äº† https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # ç»™å•ç¯‡æ–‡ç« æ·»åŠ æ ‡ç­¾ https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  #- encryptcontent: {}
      #global_password: '1221504'

markdown_extensions:
  #åˆ—è¡¨
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true
  # latexæ”¯æŒ
  - pymdownx.arithmatex: 
      generic: true
  # ç»™å›¾ç‰‡åé¢æ·»åŠ {width="300"}è®¾ç½®å¤§å°
  # æŒ‰é’®
  - attr_list 
  - md_in_html
  #é”šç‚¹
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  # ä»£ç å—
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      linenums: false # æ˜¾ç¤ºè¡Œå·
      auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.superfences # ä»£ç å—é«˜äº®æ’ä»¶
  - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonitionéœ€è¦
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables #è¡¨æ ¼
  - footnotes #æ³¨è„š
  #å›¾æ ‡
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


extra_javascript:
  # latexæ”¯æŒ
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  
  - javascripts/busuanzi.pure.mini.js
  
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
  
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - css/no-footer.css # ä¸ä½¿ç”¨åº•éƒ¨çš„ç¿»é¡µ
  - css/unordered-list-symbols.css # multiplt unordered list symbols
  - css/flink.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

